add tagging
izumin5210/hitorigoto-reporter pull request #5
Opened 2016-10-12 11:03 UTC by takose

2016-10-12 11:39 UTC, izumin5210 requested changes

2016-10-12 11:39 UTC, izumin5210 commented on lib/hitorigoto_reporter/formatter.rb
> +      filtered_list.map{ |h| h.stamps }.flatten.uniq
I think `Enumerable#flat_map` and [`&` operator](https://www.reddit.com/r/ruby/comments/2ipgx6/help_understanding_mapjoin/) make your code more smart :yum:

2016-10-12 13:07 UTC, takose commented
I have no confidence in this change.. Is this right?

2016-10-12 23:13 UTC, takose commented
I retried to fix!

2016-10-13 02:32 UTC, izumin5210 approved these changes

2016-10-13 02:33 UTC, izumin5210 commented
Good job !
![寿司ゆき:ok](https://d1zd1v0cxnbx2w.cloudfront.net/images/sets/sushiyuki/03.png)

2016-10-13 02:33 UTC, merged